### ISSUE TITLE
 File reload not working

### ISSUE THREAD

**Issue by Oxxy-k** [KarimMokhtar/react-drag-drop-files#59]
Hello, thank you for your job! I have a problem in Google Chrome when I try to reload the same file another time. If I upload a file, then change the state to null, and try to upload the same file again, the onChange or onSelect event doesn't fire. Prop value fileOrFiles={state} doesn't work

**Comment by Mohamed-Elhawary** [comment]
@Oxxy-k I have the same issue here, did you get a proper solution ??

**Comment by KarimMokhtar** [comment]
Hello @Oxxy-k , @Mohamed-Elhawary  Thank you so much for your contributions:
please be notified that this issue was solved on v.2.3.7 and above.
Thanks.

**Comment by michaenovak-cen63961** [comment]
I am on 2.3.7 and it's still not working. `handleChange` is called only the first time, on second upload of same file it is not called.

**Comment by Mykybo** [comment]
I am on 2.3.7 and it's still not working. `handleChange` is called only the first time, on second upload of same file it is not called.

**Comment by Mykybo** [comment]
i had to fix it by using a workaround with `fileOrFiles`
